# Generated by Django 2.1.7 on 2019-03-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='our_picks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=30, verbose_name='Title')),
                ('link', models.CharField(max_length=500, verbose_name='link')),
            ],
        ),
    ]
