# Generated by Django 2.1.7 on 2019-03-18 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_picks',
            name='embed',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='embed'),
            preserve_default=False,
        ),
    ]
