# Generated by Django 2.1.7 on 2019-03-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiv_vid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiv_vid',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
