# Generated by Django 2.1.7 on 2019-03-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiv_vid', '0002_auto_20190319_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiv_vid',
            name='content',
            field=models.TextField(),
        ),
    ]
